In [1]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# The original error was due to passing None as the path for a PANDAS adapter.
# When using the PANDAS adapter, a specific file within the dataset must be specified.

# Load the latest version of a specific file from the dataset
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "ravindrasinghrana/job-description-dataset",
  # Specify the name of a CSV file within the dataset.
  # This is a common filename, but you might need to adjust it
  # if the actual file has a different name (e.g., 'data.csv', 'jobs.csv').
  "job_descriptions.csv",
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:")
display(df.head())

/tmp/ipykernel_7696/2973741142.py:8: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Downloading to /root/.cache/kagglehub/datasets/ravindrasinghrana/job-description-dataset/versions/1/job_descriptions.csv...

100%|██████████| 457M/457M [00:17<00:00, 27.8MB/s]

Extracting zip of job_descriptions.csv...

First 5 records:

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,...,+1-820-643-5431x47576,Network Engineer,Wireless Network Engineer,FlexJobs,"Wireless Network Engineers design, implement, ...","{'Transportation Benefits, Professional Develo...",Wireless network design and architecture Wi-Fi...,"Design, configure, and optimize wireless netwo...",Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,...,343.975.4702x9340,Event Manager,Conference Manager,Jobs2Careers,A Conference Manager coordinates and manages c...,"{'Flexible Spending Accounts (FSAs), Relocatio...",Event planning Conference logistics Budget man...,Specialize in conference and convention planni...,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."

In [2]:
intern_count = (df['Work Type'] == 'Intern').sum()
print(f"Number of 'Intern' positions: {intern_count}")

job_portal_count = (df['Job Portal'] == 'Indeed').sum()
print(f"Number of 'Indeed' in job portal: {job_portal_count}")

job_portal_count2 = (df['Job Portal'] == 'LinkedIn').sum()
print(f"Number of 'Linkedin' in qualifications: {job_portal_count2}")

qualification_count = (df['Qualifications'] == 'B.Tech').sum()
print(f"Number of 'B.tech' in qualifications: {qualification_count}")

qualification_count2 = (df['Qualifications'] == 'M.Tech').sum()
print(f"Number of 'M.Tech' in qualifications: {qualification_count2}")

qualification_count3 = (df['Qualifications'] == 'PhD').sum()
print(f"Number of 'Phd' in qualifications: {qualification_count3}")

jobtitle_count4 = (df['Job Title'] == 'Mechanical Engineer').sum()
print(f"Number of 'Mechanical Engineeri' in job title: {jobtitle_count4}")

jobtitle_count5 = (df['Job Title'] == 'Data Scientist').sum()
print(f"Number of 'Data Scientist' in job title: {jobtitle_count5}")

jobtitle_count6 = (df['Job Title'] == 'Data Engineer').sum()
print(f"Number of 'Data Engineer' in job title: {jobtitle_count6}")

Number of 'Intern' positions: 323090
Number of 'Indeed' in job portal: 64776
Number of 'Linkedin' in qualifications: 64664
Number of 'B.tech' in qualifications: 161443
Number of 'M.Tech' in qualifications: 161719
Number of 'Phd' in qualifications: 161662
Number of 'Mechanical Engineeri' in job title: 13894
Number of 'Data Scientist' in job title: 6940
Number of 'Data Engineer' in job title: 10462

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

# Removing unnecessary columns

In [4]:
df.drop(columns=['Contact','Job Description','Benefits','skills','Responsibilities'], inplace=True)

In [5]:
df = df.rename(columns={'Job Id':'job_id',
                        'Salary Range':'salary_range',
                        'Work Type':'work_type',
                        'Company Size':'company_size',
                        'Job Posting Date':'job_post_date',
                        'Contact Person':'contact',
                        'Job Title':'job_title',
                        'Job Portal':'job_portal',})
df

,job_id,Experience,Qualifications,salary_range,location,Country,latitude,longitude,work_type,company_size,job_post_date,Preference,contact,job_title,Role,job_portal,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,2022-04-24,Female,Brandon Cunningham,Digital Marketing Specialist,Social Media Manager,Snagajob,Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,2022-12-19,Female,Francisco Larsen,Web Developer,Frontend Web Developer,Idealist,PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,2022-09-14,Male,Gary Gibson,Operations Manager,Quality Control Manager,Jobs2Careers,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,2023-02-25,Female,Joy Lucero,Network Engineer,Wireless Network Engineer,FlexJobs,Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O..."
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,2022-10-11,Female,Julie Johnson,Event Manager,Conference Manager,Jobs2Careers,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,18281,2022-05-19,Both,Shawn Cortez,Mechanical Engineer,Mechanical Design Engineer,ZipRecruiter,The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I..."
1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,63621,2023-03-14,Male,Steven Diaz,IT Manager,IT Director,USAJOBS,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":..."
1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,114287,2022-01-23,Female,Bryan Morales,Mechanical Engineer,Mechanical Design Engineer,Indeed,KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct..."
1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,45009,2021-12-28,Female,Steven Dunn,HR Coordinator,Training Coordinator,Stack Overflow Jobs,Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""..."
1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,87637,2022-10-01,Male,Jennifer Moore,Event Planner,Wedding Planner,USAJOBS,Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip..."

# General Formating for the dataset

In [6]:
df[['min_salary', 'max_salary']] = df['salary_range'].str.split('-', expand=True)
df['min_salary'] = df['min_salary'].str.replace('$', '').str.replace('K', '').astype(int)
df['max_salary'] = df['max_salary'].str.replace('$', '').str.replace('K', '').astype(int)
df['min_salary'] = df['min_salary'] * 1000
df['max_salary'] = df['max_salary'] * 1000
df

,job_id,Experience,Qualifications,salary_range,location,Country,latitude,longitude,work_type,company_size,job_post_date,Preference,contact,job_title,Role,job_portal,Company,Company Profile,min_salary,max_salary
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,2022-04-24,Female,Brandon Cunningham,Digital Marketing Specialist,Social Media Manager,Snagajob,Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie...",59000,99000
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,2022-12-19,Female,Francisco Larsen,Web Developer,Frontend Web Developer,Idealist,PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com...",56000,116000
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,2022-09-14,Male,Gary Gibson,Operations Manager,Quality Control Manager,Jobs2Careers,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P...",61000,104000
3,688192671473044,4 to 11 Years,PhD,$65K-$91K,Porto-Novo,Benin,9.3077,2.3158,Full-Time,129896,2023-02-25,Female,Joy Lucero,Network Engineer,Wireless Network Engineer,FlexJobs,Hess,"{""Sector"":""Energy"",""Industry"":""Mining, Crude-O...",65000,91000
4,117057806156508,1 to 12 Years,MBA,$64K-$87K,Santiago,Chile,-35.6751,-71.5429,Intern,53944,2022-10-11,Female,Julie Johnson,Event Manager,Conference Manager,Jobs2Careers,Cairn Energy,"{""Sector"":""Energy"",""Industry"":""Energy - Oil & ...",64000,87000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615935,134563577088850,0 to 12 Years,B.Tech,$64K-$114K,"Malabo (de jure),",Equatorial Guinea,1.6508,10.2679,Full-Time,18281,2022-05-19,Both,Shawn Cortez,Mechanical Engineer,Mechanical Design Engineer,ZipRecruiter,The Hershey Company,"{""Sector"":""Food and Beverage/Confectionery"",""I...",64000,114000
1615936,618604818190827,2 to 14 Years,M.Tech,$62K-$130K,Warsaw,Poland,51.9194,19.1451,Intern,63621,2023-03-14,Male,Steven Diaz,IT Manager,IT Director,USAJOBS,EQT,"{""Sector"":""Energy"",""Industry"":""Energy"",""City"":...",62000,130000
1615937,615471367712200,4 to 15 Years,BCA,$60K-$96K,Ashgabat,Turkmenistan,38.9697,59.5563,Part-Time,114287,2022-01-23,Female,Bryan Morales,Mechanical Engineer,Mechanical Design Engineer,Indeed,KLA,"{""Sector"":""Technology"",""Industry"":""Semiconduct...",60000,96000
1615938,804137342023945,5 to 15 Years,BCA,$65K-$103K,Ouagadougou,Burkina Faso,12.2383,-1.5616,Full-Time,45009,2021-12-28,Female,Steven Dunn,HR Coordinator,Training Coordinator,Stack Overflow Jobs,Mahindra & Mahindra,"{""Sector"":""Automotive"",""Industry"":""Automotive""...",65000,103000
1615939,404645755314484,1 to 11 Years,BBA,$56K-$109K,Asmara,Eritrea,15.1794,39.7823,Part-Time,87637,2022-10-01,Male,Jennifer Moore,Event Planner,Wedding Planner,USAJOBS,Ashtead Group,"{""Sector"":""Equipment Rental"",""Industry"":""Equip...",56000,109000

In [7]:
df.to_csv('job_descriptions_clean.csv', index=False)
print("DataFrame saved to 'job_descriptions_clean.csv'")

DataFrame saved to 'job_descriptions_clean.csv'